-   id: check-tf
    name: check tf
    description: Check if custom rules are satisfied.
    entry: tfrulecheck
    additional_dependencies: ["git+https://github.com/eieste/tfrulecheck.git@main"]
    language: python
    types: [python]