plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - "@semantic-release/git"
  - "@semantic-release/exec"

branches:
  - main

prepare:
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
  - path: "@semantic-release/exec"
    cmd: "./.github/release.bash ${lastRelease.version} ${nextRelease.version}"
  - path: "@semantic-release/git"
    assets:
      - src/tfutility/__init__.py
      - README.md
      - CHANELOG.md

publish:
  - path: "@semantic-release/github"

success:
  - "@semantic-release/github"

fail:
  - "@semantic-release/github"


repositoryUrl: git@github.com:eieste/tfutility.git
