plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - "@semantic-release/git"
  - "@semantic-release/exec"

branches:
  - main

prepare:
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
  - path: "@semantic-release/exec"
    cmd: "echo ${nextRelease.version} > VERSION"
  - path: "@semantic-release/git"
    assets:
      - VERSION
      - CHANELOG.md

publish:
  - path: "@semantic-release/github"

success:
  - "@semantic-release/github"

fail:
  - "@semantic-release/github"


repositoryUrl: git@github.com:eieste/tfutility.git
