plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - "@semantic-release/git"

branches:
  - main

prepare:
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"

publish:
  - path: "@semantic-release/github"

success:
  - "@semantic-release/github"

fail:
  - "@semantic-release/github"


repositoryUrl: git@github.com:eieste/tfutils.git
