
name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  release:
    types: [created]

  workflow_run:
    workflows: [release]
    branches: [main]
    types: 
      - completed
      
jobs:
      push-tfutility-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/eieste/tfutility:latest
              docker push ghcr.io/eieste/tfutility:latest

