
name: documentation
on:
  release:
    types: [published,created]

  workflow_run:
    workflows: [release]
    branches: [main]
    types: 
      - completed

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip3 install .[dev]
          pip3 install .
      - name: Sphinx build
        run: |
          cd docs
          make html SPHINXOPTS="-W"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true